Database Backup

In [ ]:
CREATE TABLE [dbo].[T_Beacon](
	[idBeacon] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](255) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_Beacon_Region_RSSILimits]    Script Date: 1/6/21 17:27:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_Beacon_Region_RSSILimits](
	[idRegion] [int] NULL,
	[idBeacon] [int] NULL,
	[RSSIMax] [int] NULL,
	[RSSIMin] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_Danger]    Script Date: 1/6/21 17:27:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_Danger](
	[dangerLevel] [int] NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_Measures]    Script Date: 1/6/21 17:27:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_Measures](
	[idMeasure] [int] NULL,
	[idUser] [int] NULL,
	[idBeacon] [int] NULL,
	[RSSI] [int] NULL,
	[measureTime] [datetime] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_Region]    Script Date: 1/6/21 17:27:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_Region](
	[idRegion] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](255) NULL,
	[description] [varchar](255) NULL,
	[dangerLevel] [int] NULL,
	[maxStayTimeMinutes] [int] NULL,
	[avgTemperature] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_Role]    Script Date: 1/6/21 17:27:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_Role](
	[idRole] [int] NULL,
	[description] [varchar](255) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[T_User]    Script Date: 1/6/21 17:27:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[T_User](
	[idUser] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](255) NOT NULL,
	[login] [varchar](255) NOT NULL,
	[password] [varchar](255) NOT NULL,
	[createDate] [datetime] NOT NULL,
	[active] [bit] NOT NULL,
	[idRole] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[PR_Detalhes_Region]    Script Date: 1/6/21 17:27:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[PR_Detalhes_Region]
(
	@idRegion int
)
as 
select top 1 * from T_Region where idRegion = @idRegion
GO
/****** Object:  StoredProcedure [dbo].[PR_Efetuar_Login]    Script Date: 1/6/21 17:27:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE procedure [dbo].[PR_Efetuar_Login] (
    @login varchar(255),
    @password varchar(255)
)
as
select idUser, name, idRole, login from T_User where login = @login and password = @password

GO
/****** Object:  StoredProcedure [dbo].[PR_Inserir_RSSI]    Script Date: 1/6/21 17:27:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE procedure [dbo].[PR_Inserir_RSSI] (
    @idBeacon int, 
    @idUser int,
    @RSSI int
)

as 

declare @idMeasure as int
select @idMeasure = idMeasure + 1 from (select top 1 idMeasure from T_Measures order by idMeasure desc) d

insert into T_Measures values (@idMeasure, @idUser, @idBeacon, @RSSI, GetDate())
GO
/****** Object:  StoredProcedure [dbo].[PR_Listar_MapeamentoRSSI_Regiao]    Script Date: 1/6/21 17:27:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create procedure [dbo].[PR_Listar_MapeamentoRSSI_Regiao]
(
	@idRegion int
)
as
select * from T_Beacon_Region_RSSILimits where idRegion = @idRegion
GO

Initial data setup

In [ ]:
insert into T_Beacon values ('EMBeacon12709')
insert into T_Beacon values ('EMBeacon13922')
insert into T_Beacon values ('EMBeaconXXXXX')

insert into T_Beacon_Region_RSSILimits values (1,1,-30,-100)
insert into T_Beacon_Region_RSSILimits values (1,2,-40,-110)
insert into T_Beacon_Region_RSSILimits values (1,3,-50,-90)

insert into T_Danger values (0, 'Muito Perigoso')
insert into T_Danger values (1, 'Medio')
insert into T_Danger values (2, 'Baixo perigo')

insert into T_Region values ('Sala de Corte', 'Sala onde sao cortados frangos', 2, 180, 20)
insert into T_Region values ('Freezer', 'Repositorio das carnes ja cortadas', 1, 30, -2)
insert into T_Region values ('Armazem de caixas', 'Sala onde sao armazenados caixas de papelao', 3, 240, 25)

insert into T_Role values  (0, 'Admin')
insert into T_Role values  (1, 'Funcionario')

insert into T_User values ('marcos', 'marcos', 'marcos123', getDate(), 1, 1)